### ISSUE TITLE
Refresh access token

### ISSUE THREAD

**Issue by stevenhewitt** [spotify/android-auth#28]
Hi, in my test project, I've gotten authentication and playback working, but the access token I get expires in 3600 seconds.  What's the best way to refresh the token after 1 hour? I can't seem to find anything in the android-auth sdk other than just do another `AuthenticationClient.openLoginActivity` which then interferes with the UI. Should I just try to use some Web API calls such as a POST to `https://accounts.spotify.com/api/token`? Although this requires a refresh_token, which doesn't seem accessible from the android-auth lib either.

**Comment by hughrawlinson** [comment]
Hi @stevenhewitt - in order to get a refresh token, one must use the [Authorization Code](https://spotify.github.io/android-auth/com/spotify/sdk/android/authentication/AuthenticationResponse.Type.html#CODE) oauth flow. As this flow requires the client secret, it must be implemented in a backend (the client secret MUST NOT appear in your binary). We're looking into a way to make it possible to get a refreshable grant without a backend. More info on authorization flows is available [here](https://developer.spotify.com/web-api/authorization-guide/).

**Comment by maracuja-juice** [comment]
How can this flow integrated with the android-auth library?
